[[Timetable]]
type = "mp4"
path = "filmik.mp4"
start = "08:35:00"
stop = "10:22:02"
duration = "11"

[[Timetable]]
type = "program"
name = "web-app.lnk"
start = "10:22:02"
stop = "10:23:02"

[[Timetable]]
type = "program"
name = "mspaint"
start = "10:23:02"
stop = "10:24:02"

